### ISSUE TITLE
Add following mutations

### ISSUE THREAD

**Issue by malare** [jodyphelan/tbdb#15]
I thought these mutations were worth considering: 

Gene | Mutation | Drug | Literature |  
rpoB | p.His445Tyr | rifampicin | 10.1128/AAC.01343-16
rpoB | p.His445Leu | rifampicin | 10.1128/JCM.01599-17
rpoB | p.Ser450Leu | rifampicin | 10.1128/AAC.01093-18
katG | p.Arg632Cys | isoniazid | 10.1128/AAC.01691-09
katG | p.Met420Thr | isoniazid | 10.1128/AAC.01691-09
katG | p.Trp351STOP | isoniazid | 10.5588/ijtld.18.0095
katG | p.Asp329Ala | isoniazid | 10.1128/AAC.06418-11
eis | G-6T | kanamycin | 10.1093/jac/dkr109
eis | G-10C | kanamycin | 10.1016/j.ijmyco.2015.09.001
eis | A-13G | kanamycin | 10.1073/pnas.0907925106
eis | C-15T | kanamycin | 10.1093/jac/dkr109
ethA | p.Asn345Lys | ethionamide | 10.1111/j.1469-0691.2009.02838.x;   10.1111/j.1365-2672.2010.04840.x
ethA | p.Ser266Arg | Ethionamide | 10.1128/AAC.01030-10

**Comment by jodyphelan** [comment]
Thanks, I'll have a look at these!

**Comment by jodyphelan** [comment]
I've added in those mutations which passed review!

**Comment by malare** [comment]
Thank you very much. I have additionally some mutations: 

gid | p.Gly73Ala | Streptomycin | 10.1128/AAC.02175-18
gid | p.Leu79Ser | Streptomycin | 10.1128/AAC.02175-18
gid | p.Leu108Arg | Streptomycin | 10.1128/AAC.02175-18
ethA | p.Cys137Arg | Ethionamide | 10.1128/AAC.02175-18
embB | p.Ala505Val | Ethambutol | 10.1128/AAC.02175-18
ahpC | p.Cys-57Thr | Pyrazinamide | 10.1016/S1473-3099(15)00062-6

I am sorry for the individual messages..
Best

**Comment by jodyphelan** [comment]
No Problem! I'll take a look at these, thanks for the suggestions!

**Comment by jodyphelan** [comment]
Can you double-check the last mutation? As far as I know ahpC is only associated with isoniazid resistance.

**Comment by malare** [comment]
I made a mistake. Of course the following is true:
ahpC | p.Cys-57Thr | isoniazid | 10.1016/S1473-3099(15)00062-6

Sorry and thank you!

**Comment by jodyphelan** [comment]
The mutations have undergone review and high-confidence mutations have been merged in. Thanks for the suggestions!

Jody
