### ISSUE TITLE
GyrA Ala90Gly incorrectly listed as resistant

### ISSUE THREAD

**Issue by conmeehan** [jodyphelan/tbdb#2]
Hi,

I see that the Ala90Gly muation in gyrA is listed as resisant for FQs both in this list and the online TBprofiler. However, several papers have shown thatt when by itself, this is not resistant:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3299416/
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4710215/
And some references within.

Can you please change this in the list so that the resultds are more accurate? Thanks.

**Comment by jodyphelan** [comment]
Hi Conor,

Thanks for flagging up the mutation. I've removed the mutation from the database. I also noticed that gyrB Ala90Gly was in the database but could find no mention of it in the literature. I assume this was an error in the original database and I've taken it out too.

Jody

**Comment by conmeehan** [comment]
Hi Jody,
Thats great, thanks for the quick action. I would agree that the same in the gyrB is incorrect too. Great stuf.
Cheers,
Con

**Comment by jodyphelan** [comment]
No probs!
