### ISSUE TITLE
pncA mutations to be included in tbdb

### ISSUE THREAD

**Issue by adippenaar** [jodyphelan/tbdb#22]
** Please provide a justification of adding/removing the mutation along along with the following essential information.

We are screening a particular strain responsible for an outbreak - Beijing with a characteristic pncA double mutation (Thr100Ile, Thr160Ala) - these have been phenotypically tested to be resistant to PZA in a local capacity. 

Gene: [pncA]
Mutation: [Thr100Ile]
Literature Evidence: [Genetic Determinants of Drug Resistance in Mycobacterium
tuberculosis and Their Diagnostic Value; Farhat et al. 2016 - doi:10.1128/JCM.01214-17]

Gene: [pncA]
Mutation: [Thr160Ala]
Literature Evidence: [Genetic Determinants of Drug Resistance in Mycobacterium
tuberculosis and Their Diagnostic Value; Farhat et al. 2016 - doi:10.1128/JCM.01214-17]

**Comment by jodyphelan** [comment]
Thanks Anzaan! I'll put them through the review pipeline.

Jody

**Comment by jodyphelan** [comment]
The mutations have now been added in thanks!

**Comment by adippenaar** [comment]
Thanks, Jody - great news.

Best,
Anzaan

Anzaan Dippenaar  |  PhD (SU)
Post-Doctoral Research Fellow: Department of Biomedical Sciences
Division of Molecular Biology and Human Genetics | Faculty of Medicine and Health Sciences
DST-NRF Centre of Excellence for Biomedical Tuberculosis Research | SAMRC Centre for Tuberculosis Research
e: adippenaar@sun.ac.za  |  t: +27 21 938 9957  |  a: Room 315, FISAN Building, Francie van Zijl Drive

[1512997505056_uni.jpg]
________________________________
