### ISSUE TITLE
get_genome_positions.py output

### ISSUE THREAD

**Issue by arturotorreso** [jodyphelan/tbdb#26]
Hi @jodyphelan , 

I'm getting a bit confused with the output of get_genome_positions.py. 

For example, a line like the following: 

katG	p.Ser315Ile	isoniazid	2155168	G	T

would mean that the nucleotide change G -> T is associated to isoniazid resistance. Are the G and the T as they will appear in the genome, or are they translated from C and A? I'm saying that because when I look at the position 2155168 in the reference genome H37Rv I get a C. 

Thanks, 
Arturo

**Comment by jodyphelan** [comment]
Hi @arturotorreso 

The second last column is the reference the last one is the alternate. In this case because katG is in the reverse direction it uses the reverse complement base.

Jody
