### ISSUE TITLE
Error in tbprofiler_get_genome_pos.py

### ISSUE THREAD

**Issue by jodyphelan** [jodyphelan/tbdb#27]
Thank you Jody for your inputs .
Could you please help me with getting the genomic location for mutation in tbd.csv .

I was trying with tbprofiler_get_genome_pos.py script but was unsuccessful.

_Originally posted by @Ankita-1211 in https://github.com/jodyphelan/TBProfiler/issues/109#issuecomment-660973510_

**Comment by jodyphelan** [comment]
Hi @Ankita-1211

I've transferred the issue here as the script is part of this repo.
What is the error you are getting?

Jody

**Comment by jodyphelan** [comment]
Hi @ankita-1211

Here is a [link](https://gist.githubusercontent.com/jodyphelan/0791616126024fb431e6eebb0137224a/raw/ca8572bc20e7613a686a7cbcda71f6362e6a1757/genome_pos.txt) to the genome positions. This is based on a large dataset of 30k isolates.

**Comment by Ankita-1211** [comment]
Thank you for your help.
Much appreciated
