### ISSUE TITLE
Add gyrB mutation

### ISSUE THREAD

**Issue by dmujuni** [jodyphelan/tbdb#30]
** Please provide a justification of adding/removing the mutation along along with the following essential information.

Gene: [gyrase]
Mutation: [gyrB Glu540Asp]
Literature Evidence: [https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3405621/ ; https://doi.org/10.1128/AAC.00825-17]

**Comment by jodyphelan** [comment]
Hi @dmujuni 

Thank you for the request to add a mutation. The mutation will now undergo review (see [here](https://github.com/jodyphelan/tbdb/pull/31)) and we will get back to you asap.

Jody

**Comment by jodyphelan** [comment]
The evidence from the literature seems to suggest that the mutation is associated with later-generation quinolones (moxifloxacin) but not (or low levels) with early-generation quinolones (ofloxacin, levofloxacin and ciprofloxacin). 
We have thus added in the mutation for **moxifloxacin**. Please see https://github.com/jodyphelan/tbdb/pull/31 for more details. Thanks again for the request!

Jody
