### ISSUE TITLE
Question regarding mutations

### ISSUE THREAD

**Issue by bajwamoneeb** [jodyphelan/tbdb#42]
Hi Jody,

Do you have all the WHO catalogue mutations in your database? I could not find whether you had the inhA_g-154a (fabG1_L203L) mutation. Also do you have Ser65Ser for PZA? I appreciate your help.

**Comment by jodyphelan** [comment]
Hi @bajwamoneeb 

Yes, the WHO mutations should be in the database. 

- inhA_g-15a: https://github.com/jodyphelan/tbdb/blob/master/tbdb.csv#L749-L750
- Ser65Ser: Which gene is this in? I could not find any matching mutation in thew WHO catalogue

**Comment by bajwamoneeb** [comment]
Thanks! For the second question it is regarding the _pncA_ gene. This mutation comes from CDC's TB survey of last year. They mention this mutation is not expected to confer resistance, but in their survey, 25/60 (42%) of labs reported resistance when using MGIT to grow this isolate. (0/1 reported resistance with VersaTREK).

**Comment by jodyphelan** [comment]
Thanks, for the info. This mutation is synonymous and looks like it is a phylogenetic lineage3 mutations (https://tbdr.lshtm.ac.uk/variants/pncA/c.195G>A). The tbdb list only contains mutations that actually cause resistance, so with the current criteria it does not qualify for inclusion.  If this was included, it would lead to nearly all lineage3 isolates being classified as PZA resistant, so this is probably not a good idea.

**Comment by bajwamoneeb** [comment]
Hi Jody,

I noticed actually that the sample associated with this question was classified as a lineage 4.1.1.1. The quality was decent as well.
________________________________

**Comment by bajwamoneeb** [comment]
Hi Jody, 

There is also the Leu203Leu fabg1 mutation which is associated with resistance in CDC's 2021 TB survey. Is this included in your list? See CDC's findings here: https://www.cdc.gov/tb/topic/laboratory/mpep/2020/sep-mpepIsolate.htm

**Comment by jodyphelan** [comment]
Hi @bajwamoneeb 

Yes the Leu203Leu mutation in _fabG1_ is included. It's resistance conferring effect is not due to the synonymous change but it created an alternative promoter for the _inhA_ gene and is listed as such in the database: _inhA_ c.-154G>A (https://github.com/jodyphelan/tbdb/blob/master/tbdb.csv#L749-L750). See https://pubmed.ncbi.nlm.nih.gov/24354762/ for the original description.

**Comment by bajwamoneeb** [comment]
Ok that's interesting because for the sample that the CDC sent us we couldn't find that mutation with TB-Profiler, but when we sent the FASTQ's to Wadsworth to run in their pipeline they found that mutation.

**Comment by jodyphelan** [comment]
Are you using the latest version of tb-profiler and the database?
For example here I've attached the report for the run SRR5067647 from the SRA. Maybe you could run this sample through your version and see if you get the same result?
[SRR5067647.results.txt](https://github.com/jodyphelan/tbdb/files/9242361/SRR5067647.results.txt)

**Comment by bajwamoneeb** [comment]
So I'm using the docker tags available on [quay](https://quay.io/repository/biocontainers/tb-profiler?tab=tags) for dealing with updates within the workflow I created. This should update the database as well correct?

**Comment by jodyphelan** [comment]
Yeah, if you use **4.2.0--pypyh5e36f6f_0** this should be the latest version

**Comment by bajwamoneeb** [comment]
Ah ok there was an issue in my WDL script which caused it to run without updating to the latest version. I fixed it and I do see that mutation now.

**Comment by jodyphelan** [comment]
Ah that is good to hear!

**Comment by bajwamoneeb** [comment]
Also, can you output coverage for this gene in your report at least?
________________________________
