### ISSUE TITLE
Releases/Versions

### ISSUE THREAD

**Issue by jwarnn** [jodyphelan/tbdb#44]
I think it would be useful to do releases for this repository. If this tool is used in research it would be best to be able to report a version or release data for reproducibility. TBProfiler is a great tool!

**Comment by jodyphelan** [comment]
Thanks for using the tool! At the moment the version is given using the git commit string. For example the [db currently packaged](https://github.com/jodyphelan/TBProfiler/blob/master/db/tbdb.version.json) with TB-Profiler has the following version:

```
{"commit": "4738132"}
```

Would there be an advantage to using a release over the current system?

**Comment by jwarnn** [comment]
The current system will work. For StaPH-B/docker-builds we just like to keep the tools up to date but also track versions of the software that we use for purposes of reporting and maintaining reproducibility. So for the tools that I have contributed to I will usually look biweekly to see if there are any updates to those tools. So it is just a matter of ease. I would look for a new commit in tpdb or a release of TBProfiler then make a new docker image. That way those who use a tool in their workflow can choose whether they need to update it or continue to use the older versions. So since its a marginal benefit and if it would be to much of a headache for you; the current system is great. Thank you.

**Comment by jodyphelan** [comment]
Thanks @jwarnn, If for some reason you prefer the releases in the future let me know!
