### ISSUE TITLE
Adding commit tags for the WHO branch for specific versions.

### ISSUE THREAD

**Issue by abhi18av** [jodyphelan/tbdb#62]
Hi dear @jodyphelan ,

Given the importance of the `who` branch of the database, I was wondering whether you could please tag the specific commits on the branch marking the version of the databse.

For example, `who-v1` and `who-v2` on specific tags.

This would help identify the exact commit and the corresponding version of the database that we can directly use within the MAGMA pipeline.

CC @vrennie @mdediegofuertes

**Comment by jodyphelan** [comment]
Hi @abhi18av ,

I've added a tag for WHO-v2 here: https://github.com/jodyphelan/tbdb/releases/tag/who-v2

Would this be ok?

**Comment by abhi18av** [comment]
Hi Jody,


Yes, that's perfect thank you so much 😊
