### ISSUE TITLE
Clarify version of H37Rv in docs

### ISSUE THREAD

**Issue by tseemann** [jodyphelan/tbdb#8]
"Important! The mutations and resulting library files are in reference to the H37Rv reference genome"

Can you please specify which version?   1, 2 or 3 ?  ( I assume 3)

**Comment by jodyphelan** [comment]
The reference used is GCA_000195955.2 which confusingly is the same as NC_000962.3 (not sure why they use different versions!). I've updated this in the README.

**Comment by tseemann** [comment]
Thank you.
