### ISSUE TITLE
Resistance to Bedaquiline and Delamanid 

### ISSUE THREAD

**Issue by malare** [jodyphelan/tbdb#9]
Hi @jodyphelan,

I was wondering why mutations like the following are not included in the database:

![Mutations](https://user-images.githubusercontent.com/56577974/71717024-f6067d00-2e16-11ea-80db-08367a3458e8.png)

Thank you very much

**Comment by jodyphelan** [comment]
Hi @malare,

Thanks for highlighting this. I'll take a look.

Jody

**Comment by jodyphelan** [comment]
Is the table generated from only those two references? I can't some such as the Lys250STOP.
I can also see a number of synonymous mutations, what is their role in resistance?

**Comment by malare** [comment]
Dear @jodyphelan 
I have checked the table (see above), excuse me.
Best

**Comment by jodyphelan** [comment]
Great, I've created a pull request to add in the new mutations [here](https://github.com/jodyphelan/tbdb/pull/12). After we can a couple of reviews we can add them in.

**Comment by jodyphelan** [comment]
Hi @malare I've added in the mutations now thanks for the contribution!

**Comment by malare** [comment]
I have found some additional mutations leading to delamanid resistance:
ddn | Rv3547 | p.Leu107Pro | L107P | delamanid | 10.1016/j.tube.2017.12.006
ddn | Rv3547 | 51-101   deletion |   | delamanid | 10.1016/j.tube.2017.12.006
Best

**Comment by jodyphelan** [comment]
Hi @malare, thanks for highlighting these mutations. Do you know if the deletion refers to nucleotide positions or codon positions?

**Comment by malare** [comment]
Unfortunately, this is not entirely clear. I thought they were codon positions.

**Comment by jodyphelan** [comment]
Ah right.. I'll try contact the authors. If it is codon positions then there are several possible indels on the nucleotide level.

**Comment by jodyphelan** [comment]
Got a reply... it's on the nucleotide level

**Comment by jodyphelan** [comment]
They have now been added in now!

**Comment by malare** [comment]
Some additional delamanid resistance conferring mutations:
Gly81Asp dnn delamanid 10.3343/alm.2018.38.6.563
Gly81Ser dnn delamanid 10.3343/alm.2018.38.6.563

Thank you and Best,

**Comment by jodyphelan** [comment]
Thanks! I will take a look.

Jody

**Comment by jodyphelan** [comment]
The mutations have been reviewed and Gly81Asp has been added, thanks again for the recommendation!
